name: Refresh Instagram Tokens

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:     # Manual trigger (updated)

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Call refresh-tokens endpoint
        run: |
          curl -X POST https://social-backend-6ghv.onrender.com/refresh-tokens \
            -H "X-CRON-SECRET: X36912067"

